package com.blankyin.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-23T11:42:43.118+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://cxf.blankyin.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMapPersons", targetNamespace = "http://cxf.blankyin.com/", className = "com.blankyin.cxf.GetMapPersons")
    @WebMethod
    @ResponseWrapper(localName = "getMapPersonsResponse", targetNamespace = "http://cxf.blankyin.com/", className = "com.blankyin.cxf.GetMapPersonsResponse")
    public com.blankyin.cxf.MapConvertor getMapPersons();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf.blankyin.com/", className = "com.blankyin.cxf.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf.blankyin.com/", className = "com.blankyin.cxf.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListPersons", targetNamespace = "http://cxf.blankyin.com/", className = "com.blankyin.cxf.GetListPersons")
    @WebMethod
    @ResponseWrapper(localName = "getListPersonsResponse", targetNamespace = "http://cxf.blankyin.com/", className = "com.blankyin.cxf.GetListPersonsResponse")
    public java.util.List<com.blankyin.cxf.Person> getListPersons();
}
